### ISSUE TITLE
little information errors

### ISSUE THREAD

**Issue by wormen** [nuxt/express#10]
there is a list of errors
I can understand where to look for a mistake?
you can add more debug information?

logs from pm2
```
TypeError: Cannot read property 'join' of undefined
    at _callee$ (__vue_ssr_bundle__:8511:60)
    at tryCatch (__vue_ssr_bundle__:10094:40)
    at Generator.invoke [as _invoke] (__vue_ssr_bundle__:10329:22)
    at step (__vue_ssr_bundle__:272:30)
    at __vue_ssr_bundle__:283:13
    at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:129:7)
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
TypeError: Cannot read property 'join' of undefined
    at _callee$ (__vue_ssr_bundle__:8511:60)
    at tryCatch (__vue_ssr_bundle__:10094:40)
    at Generator.invoke [as _invoke] (__vue_ssr_bundle__:10329:22)
    at step (__vue_ssr_bundle__:272:30)
    at __vue_ssr_bundle__:283:13
    at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:129:7)
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
TypeError: Cannot read property 'join' of undefined
    at _callee$ (__vue_ssr_bundle__:8511:60)
    at tryCatch (__vue_ssr_bundle__:10094:40)
    at Generator.invoke [as _invoke] (__vue_ssr_bundle__:10329:22)
    at step (__vue_ssr_bundle__:272:30)
    at __vue_ssr_bundle__:283:13
    at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:129:7)
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
TypeError: Cannot read property 'join' of undefined
    at _callee$ (__vue_ssr_bundle__:8511:60)
    at tryCatch (__vue_ssr_bundle__:10094:40)
    at Generator.invoke [as _invoke] (__vue_ssr_bundle__:10329:22)
    at step (__vue_ssr_bundle__:272:30)
    at __vue_ssr_bundle__:283:13
    at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:129:7)
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
TypeError: Cannot read property 'join' of undefined
    at _callee$ (__vue_ssr_bundle__:8511:60)
    at tryCatch (__vue_ssr_bundle__:10094:40)
    at Generator.invoke [as _invoke] (__vue_ssr_bundle__:10329:22)
    at step (__vue_ssr_bundle__:272:30)
    at __vue_ssr_bundle__:283:13
    at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:129:7)
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error: Request failed with status code 404
    at createError (/node_www/video-public.ru_express/node_modules/axios/lib/core/createError.js:15:15)
    at settle (/node_www/video-public.ru_express/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/node_www/video-public.ru_express/node_modules/axios/lib/adapters/http.js:186:11)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:186:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:122:9)
Channel is already closed can't broadcast error:
TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at process.target._send (internal/child_process.js:639:23)
    at process.send (/usr/lib/node_modules/pm2/lib/ProcessContainer.js:54:42)
    at process.uncaughtListener (/usr/lib/node_modules/pm2/lib/ProcessContainer.js:276:19)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:192:7)
    at emitPendingUnhandledRejections (internal/process/promises.js:85:22)
    at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:130:7)
```

**Comment by Atinux** [comment]
Hi @wormen 

It's not from nuxt.js itself but from what you are doing in your code.
