### ISSUE TITLE
block-scoped declarations error

### ISSUE THREAD

**Issue by uptownhr** [nuxt/express#15]
Do i need to run through babel? I'm using node v7.x.

```
npm run dev

> nuxt-express@1.0.0 dev /home/uptown/Projects/Opensource/nuxt-express
> nodemon --exec babel-node -w server.js -w nuxt.config.js -w api/ server.js

[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: server.js nuxt.config.js /home/uptown/Projects/Opensource/nuxt-express/api/**/*
[nodemon] starting `babel-node server.js`
/home/uptown/Projects/Opensource/nuxt-express/node_modules/vue-ssr-html-stream/index.js:4
class HTMLStream extends Transform {
^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/uptown/Projects/Opensource/nuxt-express/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/uptown/Projects/Opensource/nuxt-express/node_modules/vue-server-renderer/build.js:6764:18)
    at Module._compile (module.js:409:26)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by uptownhr** [comment]
false error. my local npm and node version were out of sync
